### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by lazydog97** [leyiweb/CAN_GAN_Anomaly#3]
请问代码中的abnormal是否指Dos图片（Dos作为UA类的情况下），normal是否包含正常图片以及其他三类攻击图片呢 方便的话可以给个dataset目录文件看下么 十分感谢您！

**Comment by leyiweb** [comment]
在Dos为UA的情况下
1. abnormal_class指Dos Attack
2. normal_class只包括正常的数据，其他三类已知攻击并不包括在内
3. dataset目录如下
- train
-- Normal
-- Fuzzy
-- GEAR
-- RPM
- test
-- Normal
-- Fuzzy
-- GEAR
-- RPM
-- Dos
