### ISSUE TITLE
generator找不到

### ISSUE THREAD

**Issue by dxnyxhw** [leyiweb/CAN_GAN_Anomaly#4]
安装完所需要的依赖，找不到generator
ImportError: cannot import name 'Generator' from 'networks' (/xxx/lib/python3.7/site-packages/networks/__init__.py),
求请教、指点

**Comment by leyiweb** [comment]
使用IDE吗？可能是环境问题, 根据你的路径调整下项目根目录

建议通过shell执行

**Comment by dxnyxhw** [comment]
/networks/init.py这个py文件内容是空的，下载的networks库版本是0.3.7

**Comment by leyiweb** [comment]
根据您的描述，可能是python环境异常，您可以根据文档描述，用conda安装对应版本的环境，或者提供详细的报错信息和使用方式，以便进一步排查原因

**Comment by leyiweb** [comment]
您可以参考论文中的示意图Fig4
